name = "hugo"
# 包含的运算 加 减 乘 除
ops = ["+", "-"]

[add] # a+b
min = 4 # 最小的数
max = 17 # 最大的数
limit = [10, 19] #加法结果域约束(10,20]
carry = true # 是否进位

[sub] # a-b
min = 1 # 最小的数
max = 19 # 最大的数
limit = [0, 19] #减法结果域约束(0,19]
borrow = false # 是否借位

[pdf]
path = "./pdf" # pdf保存的位置
pages = 10 # 生成页数
