name = "hugo"

# 包含的运算 加 减 乘 除
[op]
add = true
sub = true
mul = false # 暂不支持
div = false # 暂不支持

[difficulty]
min = 1 # 最小的数
max = 20 # 最大的数
limit_add = [10, 20] #加法结果域约束(10,20]
carry = false # 是否进位

[pdf]
path = "./pdf" # pdf保存的位置
pages = 10 # 生成页数
